#!/usr/bin/env python3
"""Regenerate the parts of docs/ that are derived from the source.

    python tools/gen_docs.py            # write
    python tools/gen_docs.py --check    # fail if out of date (used by CI)

Generated files carry a "do not edit" banner. Everything else in docs/ is
written by hand.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from netredact import Config  # noqa: E402
from netredact.addresses import V4_CLASSES, V6_CLASSES  # noqa: E402
from netredact.config import RULE_FAMILIES  # noqa: E402
from netredact.rules import (  # noqa: E402
    ENC,
    VAL,
    VAL_MACRO,
    RuleCatalogue,
)
from netredact.verify import (  # noqa: E402
    CONDITIONAL_CHECKS,
    IDENTITY_GATED,
    SHAPE_BLIND_FAMILIES,
    SHAPE_CHECKS,
    VERIFY_RULES,
)

BANNER = ("<!-- Generated by tools/gen_docs.py -- do not edit by hand. -->\n"
          "<!-- Run `python tools/gen_docs.py` after changing the rule tables. -->\n")

TOML_BANNER = ("# Generated by tools/gen_docs.py -- do not edit by hand.\n"
               "# Every key is shown at its default value.\n")

# a plain-English gloss per rule, so the table is useful and not just regexes
RULE_NOTES = {
    "enable-secret": "`enable secret` / `enable password`, any encoding",
    "username-secret": "`username U ... password|secret X`",
    "bare-password": "an indented `password` / `passwd` line, e.g. under `line vty`",
    "bare-secret": "a bare `secret` line, including JunOS `set ... secret`",
    "encoded-key": "any `key 0|7|8|encrypted X` anywhere on the line",
    "aaa-server-key": "`key X` on a tacacs / radius / ldap / server-private line",
    "quoted-key": "`key \"...\"`, e.g. JunOS OSPF MD5",
    "key-string": "`key-string X` in a key chain",
    "key-hash": "`key-hash <alg> X`, `hash <alg> X`",
    "license-entitlement-key": "`license keys key X` -- the entitlement key, "
                               "not the UDI",
    "snmp-community": "`snmp-server community X`, `set snmp community X`",
    "junos-community": "JunOS `community X { ... }`",
    "snmp-host": "the community or v3 user on an `snmp-server host` line",
    "snmp-v3-auth": "`auth md5|sha X`",
    "snmp-v3-priv": "`priv [aes N|des|3des] X`, cipher optional for NX-OS",
    "snmp-engineid": "`snmp-server engineID <type> X` -- identifies the device, "
                     "and is derived from a real MAC",
    "location": "the whole value of a `location` line, including FortiOS "
                "`set location`; never a JunOS `location {` stanza opener",
    "contact": "the whole value of a `contact` line, and FortiOS "
               "`set contact-info`",
    "junos-location-body": "the street address inside a JunOS "
                           "`location { ... }` stanza",
    "isakmp-key": "`crypto isakmp key X`",
    "pre-shared-key": "`pre-shared-key [address A] [key] X`",
    "auth-key": "`authentication-key` / `encryption-key`, skipping JunOS "
                "grammar keywords",
    "message-digest-key": "`message-digest-key N md5 X` (OSPF)",
    "bgp-neighbor-password": "`neighbor A password X`",
    "hsrp-vrrp-auth": "`standby N` / `vrrp N` `authentication text|md5 ... X`",
    "isis-password": "`lsp-password`, `area-password`, `domain-password`, "
                     "and the interface-level `isis password`",
    "ntp-auth-key": "`ntp authentication-key N <alg> X`",
    "ppp-credential": "`ppp chap|pap|eap password|secret|sent-username U "
                      "password X`",
    "wpa-psk": "`wpa-psk X`",
    "ftp-password": "`ip ftp|tftp|http client password X`",
    "junos-password": "`encrypted-password`, `plain-text-password-value`",
    "fortios-secret": "every FortiOS `set <attribute> <value>` credential: "
                      "`password`, `passwd`, `psksecret`, `ppk-secret`, "
                      "`auth-pwd`, `priv-pwd`, `passphrase`, `api-key`, "
                      "`secret`, `key`. The keyword must be the first token "
                      "after `set`, which is what keeps the two ordinary "
                      "words off a JunOS `set` path",
    "fortios-snmp-community": "`set name X` inside a `config system snmp "
                              "community` block. A bare `set name` is "
                              "everywhere in FortiOS, so the block is the "
                              "whole of the evidence",
    "fortios-interface-alias": "FortiOS `set alias X` on an interface. The "
                               "`set alias` in `config system global` is the "
                               "device's own name and is collected as a "
                               "hostname instead",
    "unsupported-transceiver": "Arista `service unsupported-transceiver "
                               "<label> <code>`: a TAC-issued code, and a "
                               "label that in practice carries a project name",
    "hardware-model": "a `Model:` / `Hardware:` / `Chassis type:` / `PID:` "
                      "line, where the `:` or `=` is required so the "
                      "`platform` and `model` config keywords are not "
                      "touched; and the model in Arista's `! device: <name> "
                      "(<model>, <release>)` header; and the model in "
                      "FortiOS's `#config-version=` header",
    "os-version": "a `version <digits...>` line: IOS `version 15.7`, NX-OS "
                  "`version 9.3(5)`, JunOS `version 21.4R3-S4.9;` or `set "
                  "version 23.4R2-S5.6`; the release in Arista's `! device:` "
                  "header; and the release, build and `#buildno=` / "
                  "`#branch_pt=` lines of FortiOS's `#config-version=` header",
    "software-image": "`Software image version:`, `System image file is ...`, "
                      "`Software version:`; and the bare `Junos:` / `EOS:` "
                      "forms, where a colon is required",
    "boot-image": "`boot system <image>`, commented out or not",
    "description": "a `description` or FortiOS `comments` anywhere EXCEPT on "
                   "an interface -- a VRF, a policy, a peer group. The "
                   "interface case is its own rule in its own family, one row "
                   "down",
    "acl-remark": "an ACL `remark`",
    "login-message": "`banner login`-style `message` and `announcement` text",
    "interface-description": "the same `description` line, when it is inside an "
                             "interface: `interface Gi0/0`, JunOS "
                             "`interfaces { … }`, `set interfaces … "
                             "description …`, FortiOS `set description` / "
                             "`set comments` under `config system interface`",
    "vlan-name": "the `name` under a `vlan <id>` block, and the one-line "
                 "`vlan <id> name <name>` form. Never an SVI: `interface "
                 "Vlan905` is an interface",
    "patch-name": "the name of a `patch` inside a `patch panel` block. The "
                  "`patch panel` header itself is never the value",
    "pseudowire-name": "a pseudowire name, both where it is defined under "
                       "`mpls ldp` -> `pseudowires` and where a `connector` "
                       "line refers to it (`pseudowire ldp X alternate Y`). "
                       "One rule, so a definition and its references can "
                       "never be given two different actions",
}

BLOB_NOTES = {
    "junos-type9": "any `$9$...` blob, wherever it appears",
    "crypt-hash": "any `$1$ $2a/b/x/y$ $5$ $6$ $y$` hash, wherever it appears",
    "ssh-public-key": "`ssh-rsa` / `ssh-dss` / `ssh-ed25519` / `ecdsa-sha2-*` "
                      "plus `AAAA...`, and JunOS `ssh-known-hosts` key forms",
    "license-udi": "`License UDI: ...`",
    "serial-number": "`Serial Number: ...`, `System serial number ...`",
}

BLOCK_NOTES = {
    "certificate-block": "a Cisco `certificate self-signed ... quit` body",
    "key-string-block": "a multi-line `key-string ... quit` body",
    "pem-key": "a PEM private key or DH parameter block",
    "pem-cert": "a PEM certificate block",
}

VERIFY_NOTES = {
    "crypt-hash-left": "a `$1$`/`$5$`/`$6$`-style hash survived",
    "junos-type9-left": "a JunOS `$9$` blob survived",
    "ssh-key-left": "SSH key material survived",
    "pem-left": "a `-----BEGIN` block survived -- private keys and DH "
                "parameters always, certificates only when `identity` acts",
    "type7-left": "a Cisco type-7 string survived",
    "long-hex-left": "an unexplained run of 24+ hex characters",
    "long-base64-left": "an unexplained run of 40+ base64 characters",
    "credential-left": "a credential keyword not followed by a placeholder",
    "email-left": "an e-mail address survived",
    "ipv4-left": "an IPv4 address survived whose class `[ipv4]` acts on",
    "ipv6-left": "an IPv6 address survived whose class `[ipv6]` acts on",
    "mac-left": "a recognisable MAC address survived while `[macs]` acts",
    "operational-name-left": "a supported operational name survived",
    "as-number-left": "an ASN survived in supported explicit grammar",
    "location-left": "an explicit physical location survived",
}

#: what switches a conditional check on. Unconditional checks say so.
VERIFY_GATE = {
    "email-left": '`[policy] emails` is not `"keep"`',
    "ipv4-left": "some `[ipv4]` class acts",
    "ipv6-left": "some `[ipv6]` class acts",
    "mac-left": "either `[macs]` half acts",
    "operational-name-left": "some `[operational-names]` type acts",
    "as-number-left": '`[as-numbers] default` is not `"keep"`',
    "location-left": "the matching `[locations]` rule acts",
    "ssh-key-left": '`[policy] identity` is not `"keep"`',
    "pem-left": "always for a private key; the certificate half needs "
                "`identity` to act",
}

#: appended to the gate column for a check that only knows a shape
_BLIND_NOTE = (" -- blind to spans a kept "
               + " / ".join(f"`{f}`" for f in SHAPE_BLIND_FAMILIES)
               + " rule matched")


def md_cell(text: str) -> str:
    """Escape a regex so it survives a markdown table cell."""
    return text.replace("|", "\\|")


#: the keyword-lookahead group ``rules._not_keyword`` builds: an alternation
#: of bare words followed by ``(?![-\w])``. Its source is a *set*, so the order
#: the words come out in changes from process to process -- which would make
#: this file un-regeneratable. Longest-first is the only ordering that matters
#: for matching, so equal-length words are put in alphabetical order here.
_ALT_WORD = r"(?:[\w.+-]+|\\d\+)"
_KEYWORD_ALT = re.compile(
    rf"\(\?:({_ALT_WORD}(?:\|{_ALT_WORD})+)\)\(\?!\[-\\w\]\)")


def _stable_alt(m: re.Match) -> str:
    words = sorted(m.group(1).split("|"), key=lambda w: (-len(w), w))
    return "(?:" + "|".join(words) + r")(?![-\w])"


def pattern_text(pattern: str) -> str:
    """One regex on one line, with the placeholders folded back in.

    Deliberately *not* escaped for a markdown table. Every pattern in the
    generated page lives in a fenced block instead, for two reasons. A table
    cell has to escape `|`, which is the alternation operator -- so what the
    old table printed could not be pasted into a regex tester without editing
    it first, in a document whose whole job is to be audited against the
    code. And a 400-character run with no space in it has nowhere to wrap, so
    one such cell forced the entire table sideways and pushed the rule names
    off the screen.
    """
    out = _KEYWORD_ALT.sub(_stable_alt, pattern)
    out = out.replace(ENC, "<ENC>").replace(VAL, "<VAL>")
    return re.sub(r"\s+", " ", out).strip()


def block(text: str) -> str:
    """One regex as a fenced code block."""
    return f"```\n{text}\n```"


def family_counts() -> str:
    counts = Counter(info.family for info in RuleCatalogue.builtins().inventory())
    return ", ".join(f"{counts[f]} `{f}`" for f in RULE_FAMILIES if counts[f])


def rules_md() -> str:
    catalogue = RuleCatalogue.builtins().inventory()
    names = [info.name for info in catalogue]
    out = [BANNER, "# Rule reference\n",
           "Every named rule, the family it belongs to, and every check the",
           "verification pass runs afterwards. Generated from the source, so it",
           "matches the code exactly.\n",
           f"**{len(names)} rules**: {family_counts()}.\n",
           f"- {len(VERIFY_RULES) + len(CONDITIONAL_CHECKS)} verification checks\n",
           "A rule does not decide what happens to what it finds. Its **family**",
           "does, and every family of rules is a section: the action is",
           "`[<family>] <rule>` if that key is set, otherwise `[<family>]",
           "default`. So switching one rule off is `[secrets] enable-secret =",
           "\"keep\"`, and `netredact --list-rules` prints the same names next",
           "to the section each belongs to.\n",
           "## Placeholders used in the patterns\n",
           "Three tokens stand in for material that recurs in every pattern.\n",
           "`<ENC>` -- the optional encoding or algorithm hint between a keyword",
           "and its secret:\n",
           block(ENC), "",
           "`<VAL>` -- the value matcher: a quoted string, or a run of",
           "characters that is neither space nor `;`:\n",
           block(VAL), "",
           f"`{VAL_MACRO}` -- `<VAL>` as a *capturing* group.\n",
           "## How a pattern says where the value is\n",
           "There is no `mode` field. The shape of the pattern carries it:\n",
           "- **No capture groups** -- the pattern is a *prefix*: everything up to",
           "  and including the keyword that introduces the value. netredact appends",
           "  `<VAL>` itself, so quoting, JunOS `;` terminators and trailing",
           "  `## SECRET-DATA` comments are handled for you, and a brace-only token",
           "  (`location {`) is refused so a stanza opener is never eaten.",
           "- **With capture groups** -- every group is a target span, and everything",
           "  outside the groups is kept verbatim. That is how a rule carries several",
           f"  values on one line. Write `{VAL_MACRO}` to borrow `<VAL>` as a group.\n",
           "One rule needs code rather than a span: `snmp-host` walks the tokens of",
           "an `snmp-server host` line, so the keywords survive and only the",
           "community or v3 user name is acted on.\n",
           "## Scope: the block a line is inside\n",
           "Some material is only recognisable from what encloses it. A bare",
           "`name CUST000000000123` is a VLAN name under `vlan 905` and a",
           "route-map name under `route-map`, and the line itself cannot tell you",
           "which. So a rule may name the block it needs, or the blocks it must",
           "stay out of, and three kinds of block share one set of names:\n",
           "JunOS stanzas, IOS-style blocks, FortiOS `config <path>` … `end`",
           "blocks and one-line JunOS `set` commands share the scope names",
           "shown in the rule catalogue below.\n",
           "Where the dialects share the block the name is JunOS's own —",
           "`interfaces`, `vlans`, `snmp` — so one rule covers every dialect: an",
           "IOS `interface Gi0/0` block, a JunOS `interfaces { … }` stanza, a",
           "FortiOS `config system interface` block and a `set interfaces …",
           "description …` line are all inside `interfaces`.",
           "A block only one vendor has keeps its own name: `patch-panel`,",
           "`system-admin`. Any other unindented line ends an IOS-style block,",
           "including the bare `!`; a FortiOS block ends at its own `end`, and",
           "a nested `config` inside an `edit` nests rather than replaces.\n",
           "`interface Vlan905` is scope `interfaces`, not `vlans`: an SVI is a",
           "port, and only a `vlan <id>` block defines a VLAN.\n",
           "This is also what `[[custom]] stanza` sets, so a custom rule can be",
           "restricted to a block on any vendor, not only a JunOS stanza.\n",
           "## Dialects are labelled, not gated\n",
           "Some rules only make sense in one vendor's grammar, and the table",
           "below says which — `arista` on `patch-name`, `juniper` on",
           "`junos-type9`, `fortinet` on `fortios-secret`. That label is",
           "documentation. **Every rule is applied",
           "to every file**, and nothing netredact does depends on the vendor it",
           "reports.\n",
           "That is deliberate, and the reason is the detector. Vendor detection",
           "is a whole-file heuristic reading exactly the material the",
           "`platform` family exists to delete, and it answers `unknown` for the",
           "input a redaction tool is handed most often: a pasted fragment with",
           "no header on it. A rule that fired only when the detector agreed",
           "would skip credential rules on a misread file, silently, and",
           "`--strict` would still exit 0 — a fail-open path in a tool whose",
           "promise is fail-safe.\n",
           "So a vendor-specific rule is confined by **evidence in the file**",
           "instead. `patch-name` cannot fire on a JunOS config because it has",
           "to be inside a `patch panel` block, and that grammar opens none.",
           "Scope is the gate; the dialect column is a caption.\n",
           "## Rule catalogue\n",
           "The catalogue owns whether a rule is matched at the start of a line,",
           "searched inline, or consumed as structured multi-line material.\n",
           "Each rule name links to its pattern, which is listed in full under",
           "[rule patterns](#rule-patterns) below.\n",
           "| Rule | Family | Matches | Where |",
           "|---|---|---|---|"]
    notes = RULE_NOTES | BLOB_NOTES | BLOCK_NOTES | {
        "banner": "`banner <type> <delim>` through its closing delimiter"}
    for info in catalogue:
        note = md_cell(notes.get(info.name, ""))
        scope = f"inside `{info.required_scope}`" if info.required_scope else ""
        if info.excluded_scopes:
            scope += " " + " ".join(
                f"outside `{name}`" for name in info.excluded_scopes)
        if info.vendor:
            note += f" -- {info.vendor} grammar"
        out.append(f"| [`{info.name}`](#{info.name}) | `{info.family}` | "
                   f"{note} | {scope} |")

    out += [""]

    # -- the patterns themselves, one fenced block each ------------------
    out += ["## Rule patterns\n",
            "One block per rule, in catalogue order, exactly as the code holds",
            "it bar the `<ENC>` / `<VAL>` placeholders above -- so a pattern can",
            "be copied straight into a regex tester and checked against the",
            "claim its catalogue row makes. A rule that consumes a multi-line",
            "block also carries the pattern that ends it.\n"]
    for info in catalogue:
        out += [f"### `{info.name}`\n", block(pattern_text(info.pattern)), ""]
        if info.end_pattern:
            out += ["Ends at:\n", block(pattern_text(info.end_pattern)), ""]

    out += ["## Verification checks\n",
            "Credential checks are unconditional: they fire even when the policy",
            "deliberately keeps a secret, which is why a config that keeps one",
            "still fails `--strict`, and nothing in this table ever exempts",
            "`secrets`. The conditional checks are the opposite case -- a value",
            "you chose to keep is not a miss -- so they run only when their",
            "family acts.\n",
            "A third group only recognises a *shape*:",
            ", ".join(f"`{c}`" for c in SHAPE_CHECKS) + ". A long base64 run is",
            "an authorised SSH key or a leaked one, and the check cannot tell",
            "which, so those four are blinded to the spans that a kept",
            " / ".join(f"`{f}`" for f in SHAPE_BLIND_FAMILIES)
            + " rule matched -- including the body of a kept",
            "block. A kept `secrets` rule never blinds anything.\n",
            "| Check | Fires when | Gated by |", "|---|---|---|"]
    for name, _ in VERIFY_RULES:
        gate = VERIFY_GATE.get(name, "always" if name not in IDENTITY_GATED else "")
        if name in SHAPE_CHECKS:
            gate += _BLIND_NOTE
        out.append(f"| `{name}` | {VERIFY_NOTES.get(name, '')} | {gate} |")
    for name in CONDITIONAL_CHECKS:
        out.append(f"| `{name}` | {VERIFY_NOTES.get(name, '')} | "
                   f"{VERIFY_GATE.get(name, '')} |")
    out.append("")
    return "\n".join(out)


def address_classes_table() -> tuple[str, str]:
    out = ["| Class | Prefixes | RFC | Description |", "|---|---|---|---|"]
    for name, prefixes, rfc, desc in V4_CLASSES:
        out.append(f"| `{name}` | {', '.join(f'`{p}`' for p in prefixes)} "
                   f"| {rfc} | {desc} |")
    out.append("| `well_known` | the addresses in `well_known_resolvers` | -- "
               "| public resolvers |")
    out.append("| `other_unicast` | everything else | -- "
               "| globally routable space |")
    v6 = ["| Class | Prefixes | RFC | Description |", "|---|---|---|---|"]
    for name, prefixes, rfc, desc in V6_CLASSES:
        v6.append(f"| `{name}` | {', '.join(f'`{p}`' for p in prefixes)} "
                  f"| {rfc} | {desc} |")
    v6.append("| `well_known` | the addresses in `well_known_resolvers` | -- "
              "| public resolvers |")
    v6.append("| `other_unicast` | everything else | -- | global unicast |")
    return "\n".join(out), "\n".join(v6)


def classes_md() -> str:
    v4, v6 = address_classes_table()
    return "\n".join([
        BANNER, "# Address classes\n",
        "Every address netredact sees is put into exactly **one** class. The",
        "classes are mutually exclusive and checked most-specific first, so one",
        "key in `[ipv4]` or `[ipv6]` governs any given address with no",
        "ambiguity. `default` covers every class you do not name, which is what",
        "makes the partition complete.\n",
        "Each class takes an action: `keep`, `pseudo`, `hash` or `redact`.",
        "`pseudo` moves the address inside a pool and preserves the equality",
        "relation; `hash` writes `<IP-a1b2c3>` / `<IP6-a1b2c3>`; `redact` writes",
        "the RFC-reserved constant `192.0.2.0` / `2001:db8::`, which destroys it.\n",
        "There is deliberately no `rfc5735` class. RFC 5735 is a *set* of these",
        "ranges, so a single key for it would overlap `rfc1918`, `loopback`,",
        "`multicast` and others, and the precedence between them would be",
        "arbitrary. Each range is named for what it is instead.\n",
        "## IPv4 -- `[ipv4]`\n", v4,
        "\n## IPv6 -- `[ipv6]`\n", v6,
        "\n## Always exempt\n",
        "**Netmasks and wildcard masks are never touched**, whatever you set.",
        "They are detected structurally: a dotted quad is treated as a mask when",
        "either it or its complement is of the form `1*0*`, which covers",
        "`255.255.255.0`, `0.0.0.255`, `0.0.0.0` and `255.255.255.255`.",
        "Substituting a mask would break the configuration.\n",
        "`keep_networks` is an escape hatch on top of the classes: prefixes",
        "listed there survive even when their class acts -- useful to keep one",
        "management prefix readable.\n",
        "## How pseudonyms are allocated\n",
        "IPv4 keeps its **host octet and prefix length**; only the /24 moves, into",
        "`[ipv4] pool` (default `198.18.0.0/15` then `100.64.0.0/10`). Two",
        "addresses that shared a /24 still share one afterwards, so link",
        "adjacencies and ACLs continue to make sense.\n",
        "IPv6 keeps its **interface identifier**; only the /64 moves, into",
        "`[ipv6] pool` (default `2001:db8::/32`).\n",
        "### Pool capacity is a hard limit\n",
        "One /24 of pool is consumed per **distinct source /24**, for as long as",
        "the run lasts. A pool entry holds `1 << (24 - prefixlen)` of them:",
        "a `/15` is 512, a `/10` is 16384, and the default",
        "`[\"198.18.0.0/15\", \"100.64.0.0/10\"]` is 16896. IPv6 is counted the",
        "same way in /64s: `1 << (64 - prefixlen)`, so the default `/32` holds",
        "4.3 billion and is never the constraint.\n",
        "Run out and the run **fails outright** --",
        "`RuntimeError: exhausted the v4net pseudonym space` -- rather than",
        "reusing a pseudonym and silently merging two subnets. A large",
        "service-provider configuration can easily carry more than 512 distinct",
        "/24s, so a pool narrowed to one `/15` is not enough for one: size the",
        "pool for the biggest file you will feed it, not the one in front of",
        "you.\n",
        "The two pressures pull in opposite directions. A wider pool is more",
        "capacity; a narrower one is less chance of overlapping space the",
        "configuration really uses. Acting on the overlapping *class* resolves",
        "both at once -- with `cgnat` pseudonymised, no real CGNAT address is",
        "left in the output to be confused with a generated one, so the full",
        "`100.64.0.0/10` is free to be pool.\n",
        "### Pool collisions\n",
        "The default IPv4 pool includes `100.64.0.0/10`. If your configuration",
        "really uses CGNAT and `cgnat` is left at `keep`, the output will contain",
        "real and generated addresses that look alike. netredact detects this and",
        "warns, naming both fixes: move the pool with",
        "`pool = [\"198.18.0.0/15\"]`, or give `cgnat` an action so that space",
        "moves too.\n",
        "It is also why a second pass over already-pseudonymised output",
        "**re-maps** pool addresses instead of leaving them alone: treating a",
        "pool address as \"already done\" would leak a real CGNAT address that",
        "happened to land in the pool. So `hash` and `redact` are fully",
        "idempotent -- their output is recognisably netredact's -- while `pseudo`",
        "on an address or a MAC is not: the substitute is deliberately",
        "indistinguishable from a real value, including to netredact itself.\n",
    ])


def annotated_toml() -> str:
    return TOML_BANNER + Config().to_toml()


TARGETS = {
    "docs/rules.md": rules_md,
    "docs/address-classes.md": classes_md,
    "docs/examples/annotated.toml": annotated_toml,
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any generated file is out of date")
    args = ap.parse_args()

    stale = []
    for rel, fn in TARGETS.items():
        path = ROOT / rel
        wanted = fn()
        current = path.read_text() if path.exists() else None
        if current == wanted:
            continue
        if args.check:
            stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(wanted)
            print(f"wrote {rel}")
    if stale:
        print("out of date: " + ", ".join(stale), file=sys.stderr)
        print("run: python tools/gen_docs.py", file=sys.stderr)
        return 1
    if args.check:
        print("docs up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
